### PR TITLE
Add test init and vendor dependencies

### PR DESCRIPTION
**Pull request by 46bit**
## What

PR #14 setup a Travis environment for running tests, but I encountered problems with `dep` when I added an init file for Ginkgo tests. As we're committing `vendor`ed dependencies in our projects, it makes sense to do that here.

## How to review

Code review.

## Who can review

Not @46bit.

### CODE REVIEW

**Comment by alext** [comment]
Along with this, it's probably best to update the Travis config so that the install step is a no-op (eg https://github.com/alphagov/paas-rds-broker/blob/master/.travis.yml#L19-L21).

**Comment by 46bit** [comment]
@alext With dependencies vendored, Go 1.8 Travis fails because it tries to run the tests of the `vendor` packages. https://golang.org/doc/go1.9#vendor-dotdotdot in 1.9 changes what `./...` means to exclude `vendor`. As such, once this PR is merged the tests will *already* fail under Go 1.8. Do you think we still need a test of the duplicate env variable functionality?

**Comment by 46bit** [comment]
I discussed IRL with Alex and we've decided to make the tests run under Go 1.8. That work is already done in this PR, so it's ready for review.

**Comment by camelpunch** [comment]
Uh-oh.

```
$ make test
go vet
go test 
Running Suite: Conduit
======================
Random Seed: 1511351174
Will run 0 of 0 specs


Ran 0 of 0 Specs in 0.000 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
```

**Pull request merged**
